# Generated by Django 5.0.6 on 2024-05-21 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0008_alter_products_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Customers',
            new_name='customer',
        ),
    ]
