# Generated by Django 5.0.6 on 2024-05-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0010_rename_products_product_alter_orders_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorys',
        ),
    ]
