# Generated by Django 5.0.6 on 2024-05-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0012_rename_categorys_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='password',
        ),
    ]
