# Generated by Django 5.0.6 on 2024-05-22 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0019_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='name',
        ),
    ]
